FROM node:22.14.0-slim AS builder
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --non-interactive
COPY . .
ENV VITE_API_URL=https://shard-api.notefade.com
RUN yarn build:prod

FROM scratch
COPY --from=builder /app/dist /dist
