name = "notefade-shard-api"
main = "worker/index.ts"
compatibility_date = "2024-12-01"

# Development KV namespace (preview)
[[kv_namespaces]]
binding = "SHARDS"
id = "${CF_KV_SHARDS_ID}"
preview_id = "${CF_KV_SHARDS_PREVIEW_ID}"

# Production environment
[env.production]
routes = [{ pattern = "shard-api.notefade.com", custom_domain = true }]

[[env.production.kv_namespaces]]
binding = "SHARDS"
id = "${CF_KV_SHARDS_ID}"
